### ISSUE TITLE
IDE execption with auto complete menu after updaten to 2018.3

### ISSUE THREAD

**Issue by fvollmer** [IETS3/iets3.opensource#154]
I just updated to MPS2018.3 and now I always get an exception when I try to to use the auto complete menu. 

I'm not 100% certain that this is not a setup error, but to make it easier to reproduce I started with clean MPS settings (`rm -r ~/.MPS2018.3/`) and recompiled the master of `iets3.opensource`, `mbeddr.core` and `MPS-extensions` with gradle.

Then I opened `MPS-extensions/code`, `mbeddr.core/code/languages/com.mbeddr.mpsutil` and `iets3.opensource` in mps 2018.3. Inside the iets3 project I opened Test Suite Lambda and tried the auto complete (ctrl+space). This auto complete menu is empty because of the following IDE error:

```
Exception while creating substitute actions in class jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo

java.lang.NoSuchMethodError: jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart.<init>(Lorg/jetbrains/mps/openapi/language/SConcept;Lorg/jetbrains/mps/openapi/language/SReferenceLink;)V
	at org.iets3.core.expr.adt.editor.AlgebraicConstructorType_SubstituteMenu$SMP_ReferenceScope_648dk3_a.<init>(AlgebraicConstructorType_SubstituteMenu.java:50)
	at org.iets3.core.expr.adt.editor.AlgebraicConstructorType_SubstituteMenu.getParts(AlgebraicConstructorType_SubstituteMenu.java:29)
	at jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase.createMenuItems(SubstituteMenuBase.java:44)
	at org.iets3.core.expr.adt.editor.AlgebraicConstructorType_SubstituteMenu.createMenuItems(AlgebraicConstructorType_SubstituteMenu.java:40)
	at jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase.createMenuItems(SubstituteMenuBase.java:30)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuItemFactory.createItems(DefaultSubstituteMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuItemFactory.createItems(DefaultSubstituteMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuContext.createItems(DefaultSubstituteMenuContext.java:146)
	at org.iets3.core.expr.adt.editor.GrammarActionsDescriptor$3.query(GrammarActionsDescriptor.java:186)
	at org.iets3.core.expr.adt.editor.GrammarActionsDescriptor.getActions(GrammarActionsDescriptor.java:239)
	at com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart$1.translate(GrammarCellsSubstituteMenuPart.java:35)
	at com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart$1.translate(GrammarCellsSubstituteMenuPart.java:1)
	at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:12)
	at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:7)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.moveToNext(TranslatingSequence.java:82)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.hasNext(TranslatingSequence.java:37)
	at jetbrains.mps.internal.collections.runtime.ListSequence.fromIterable(ListSequence.java:122)
	at jetbrains.mps.internal.collections.runtime.AbstractSequence.toListSequence(AbstractSequence.java:215)
	at com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart.createItems(GrammarCellsSubstituteMenuPart.java:37)
	at com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsSubstituteMenuPart.createItems(GrammarCellsSubstituteMenuPart.java:1)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase.createMenuItems(SubstituteMenuBase.java:44)
	at org.iets3.core.expr.adt.editor.GrammarCellsSubstituteMenu_AlgebraicTerm.createMenuItems(GrammarCellsSubstituteMenu_AlgebraicTerm.java:38)
	at jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase.createMenuItems(SubstituteMenuBase.java:30)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuItemFactory.createItems(DefaultSubstituteMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuItemFactory.createItems(DefaultSubstituteMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuContext.createItems(DefaultSubstituteMenuContext.java:146)
	at jetbrains.mps.lang.editor.menus.substitute.DefaultConceptMenusSubstituteMenuPart.createItemsForConcept(DefaultConceptMenusSubstituteMenuPart.java:43)
	at jetbrains.mps.lang.editor.menus.substitute.DefaultConceptMenusSubstituteMenuPart.createItemsForConcept(DefaultConceptMenusSubstituteMenuPart.java:30)
	at jetbrains.mps.lang.editor.menus.ConceptMenusPart.createItems(ConceptMenusPart.java:43)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.lang.editor.menus.substitute.DefaultConceptSubstituteMenuPart.createItems(DefaultConceptSubstituteMenuPart.java:50)
	at jetbrains.mps.lang.editor.menus.substitute.DefaultConceptSubstituteMenuPart.createItems(DefaultConceptSubstituteMenuPart.java:34)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase.createMenuItems(SubstituteMenuBase.java:44)
	at jetbrains.mps.lang.editor.menus.substitute.ImplicitSubstituteMenu.createMenuItems(ImplicitSubstituteMenu.java:54)
	at jetbrains.mps.lang.editor.menus.substitute.ImplicitSubstituteMenu.createMenuItems(ImplicitSubstituteMenu.java:34)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuItemFactory.createItems(DefaultSubstituteMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuItemFactory.createItems(DefaultSubstituteMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.substitute.DefaultSubstituteMenuContext.createItems(DefaultSubstituteMenuContext.java:146)
	at jetbrains.mps.lang.editor.menus.transformation.SubstituteItemsCollector.collect(SubstituteItemsCollector.java:83)
	at jetbrains.mps.lang.editor.menus.transformation.IncludeSubstituteMenuTransformationMenuPart.createItems(IncludeSubstituteMenuTransformationMenuPart.java:58)
	at jetbrains.mps.lang.core.editor.BaseConcept_TransformationMenu$TMP_IncludeSM_m082ag_a0.createItems(BaseConcept_TransformationMenu.java:60)
	at jetbrains.mps.lang.core.editor.BaseConcept_TransformationMenu$TMP_IncludeSM_m082ag_a0.createItems(BaseConcept_TransformationMenu.java:51)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.transformation.TransformationMenuBase.createMenuItems(TransformationMenuBase.java:43)
	at jetbrains.mps.lang.core.editor.BaseConcept_TransformationMenu.createMenuItems(BaseConcept_TransformationMenu.java:35)
	at jetbrains.mps.lang.core.editor.BaseConcept_TransformationMenu.createMenuItems(BaseConcept_TransformationMenu.java:22)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuContext.createItems(DefaultTransformationMenuContext.java:206)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:43)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:29)
	at jetbrains.mps.lang.editor.menus.ConceptMenusPart.createItems(ConceptMenusPart.java:43)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.transformation.TransformationMenuBase.createMenuItems(TransformationMenuBase.java:43)
	at jetbrains.mps.lang.editor.menus.transformation.ImplicitTransformationMenu.createMenuItems(ImplicitTransformationMenu.java:47)
	at jetbrains.mps.lang.editor.menus.transformation.ImplicitTransformationMenu.createMenuItems(ImplicitTransformationMenu.java:34)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuContext.createItems(DefaultTransformationMenuContext.java:206)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:43)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:29)
	at jetbrains.mps.lang.editor.menus.ConceptMenusPart.createItems(ConceptMenusPart.java:43)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.transformation.TransformationMenuBase.createMenuItems(TransformationMenuBase.java:43)
	at jetbrains.mps.lang.editor.menus.transformation.ImplicitTransformationMenu.createMenuItems(ImplicitTransformationMenu.java:47)
	at jetbrains.mps.lang.editor.menus.transformation.ImplicitTransformationMenu.createMenuItems(ImplicitTransformationMenu.java:34)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuContext.createItems(DefaultTransformationMenuContext.java:206)
	at jetbrains.mps.nodeEditor.cellMenu.TransformationMenuSubstituteInfo.createActions(TransformationMenuSubstituteInfo.java:66)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.getActions(AbstractNodeSubstituteInfo.java:185)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.lambda$getMatchingActions$1(AbstractNodeSubstituteInfo.java:158)
	at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
	at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:73)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:54)
	at jetbrains.mps.smodel.ModelAccessHelper.runReadAction(ModelAccessHelper.java:44)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.getMatchingActions(AbstractNodeSubstituteInfo.java:157)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteInfoFilterDecorator.lambda$getMatchingActions$0(NodeSubstituteInfoFilterDecorator.java:57)
	at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
	at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:73)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:54)
	at jetbrains.mps.smodel.ModelAccessHelper.runReadAction(ModelAccessHelper.java:44)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteInfoFilterDecorator.getMatchingActions(NodeSubstituteInfoFilterDecorator.java:51)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooserHandler.lambda$getMatchingActions$2(NodeSubstituteChooserHandler.java:162)
	at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.doExecute(TypeContextManager.java:270)
	at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.execute(TypeContextManager.java:243)
	at jetbrains.mps.typesystem.inference.TypeContextManager.runTypeCheckingComputation(TypeContextManager.java:122)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooserHandler.getMatchingActions(NodeSubstituteChooserHandler.java:159)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooserHandler.lambda$getOnlyActionToExecute$1(NodeSubstituteChooserHandler.java:102)
	at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
	at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:84)
	at jetbrains.mps.smodel.WorkbenchModelAccess.lambda$runReadAction$0(WorkbenchModelAccess.java:80)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:77)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:54)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooserHandler.runRead(NodeSubstituteChooserHandler.java:168)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooserHandler.getOnlyActionToExecute(NodeSubstituteChooserHandler.java:93)
	at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooserHandler.tryToSubstituteImmediately(NodeSubstituteChooserHandler.java:76)
	at jetbrains.mps.nodeEditor.EditorComponent.activateNodeSubstituteChooser(EditorComponent.java:2379)
	at jetbrains.mps.nodeEditor.EditorComponent.activateNodeSubstituteChooser(EditorComponent.java:2361)
	at jetbrains.mps.nodeEditor.NodeEditorActions$Complete.execute(NodeEditorActions.java:672)
	at jetbrains.mps.nodeEditor.actions.CellActionExecuter.lambda$execute$1(CellActionExecuter.java:61)
	at jetbrains.mps.nodeEditor.EditorContext.lambda$runWithContextCell$3(EditorContext.java:267)
	at jetbrains.mps.nodeEditor.EditorContext.runWithContextCell(EditorContext.java:278)
	at jetbrains.mps.nodeEditor.EditorContext.runWithContextCell(EditorContext.java:266)
	at jetbrains.mps.nodeEditor.actions.CellActionExecuter.execute(CellActionExecuter.java:52)
	at jetbrains.mps.nodeEditor.actions.ActionHandlerImpl.executeAction(ActionHandlerImpl.java:41)
	at jetbrains.mps.nodeEditor.selection.EditorCellSelection.executeAction(EditorCellSelection.java:164)
	at jetbrains.mps.nodeEditor.selection.EditorCellLabelSelection.executeAction(EditorCellLabelSelection.java:171)
	at jetbrains.mps.ide.editor.actions.Complete_Action.doExecute(Complete_Action.java:59)
	at jetbrains.mps.workbench.action.BaseAction$2.run(BaseAction.java:150)
	at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:160)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This error also occurs for me if I try to use the auto complete with my own project, which uses iets3. Any hints? My next step would be to attach intelliJ to MPS or to just downgrade to 2018.2.

**Comment by fvollmer** [comment]
I also tested this with the `maintenance/mps20182` branch and had no problems. I guess I'll go back to 2018.2 for now.

**Comment by fvollmer** [comment]
Nevermind. I tried again with 2018.3.1 and couldn't reproduce it.
